# RISK_CLAUSES rimosse su richiesta utente (solo Relazioni Specifiche)


RELATIONSHIP_CLAUSES = {
    "LAVORATIVA": { 
        "header_suffix": "RELAZIONE LAVORATIVA",
        "intro_text": "Protocollo operativo per la massimizzazione dell'efficienza e la minimizzazione delle frizioni interpersonali in ambito lavorativo.",
        "levels": {
            1: {
                "title": "STANDARD DI EFFICIENZA OPERATIVA",
                "subtitle": "(Regolamento quadro per la massimizzazione della produttività e il decoro formale)",
                "clauses": [
                    {"id": "Art. 1.1", "title": "Protocollo di Denominazione Asettica", "text": "Viene sancito il divieto assoluto e inderogabile per i Contraenti di fare ricorso ad appellativi, soprannomi, diminutivi, abbreviazioni confidenziali o vezzeggiativi di qualsiasi natura. I Soggetti sono tenuti a riferirsi l'uno all'altro esclusivamente mediante l'utilizzo del cognome anagrafico o del titolo professionale esteso, prescindendo totalmente dall'anzianità di servizio maturata o dal grado di confidenza pregressa, al fine di azzerare ogni connotazione emotiva nello scambio verbale."},
                    {"id": "Art. 1.2", "title": "Sterilizzazione del Perimetro Tematico", "text": "Sono tassativamente interdette le interazioni verbali riguardanti la sfera privata, le condizioni meteorologiche, gli eventi sportivi, le preferenze alimentari o qualsiasi altro argomento classificabile come 'Small Talk'. Il perimetro discorsivo ammesso è strettamente e rigidamente limitato alle sole mansioni operative dirette. Ogni deviazione da tale standard è formalmente classificata come 'Rumore Informativo Non Produttivo' e soggetta a richiamo."},
                    {"id": "Art. 1.3", "title": "Distanziamento Prossemico Operativo", "text": "Nello svolgimento delle attività lavorative in presenza, le Parti hanno l'obbligo di garantire e mantenere un distanziamento fisico reciproco non inferiore a centimetri 120 (centoventi), in conformità allo standard prossemico definito 'Zona Sociale'. È severamente vietato l'ingresso, anche momentaneo, nella 'Zona Intima' (raggio inferiore a 45 cm) del collega, atto che verrà classificato come tentativo di intimidazione territoriale o ricerca di complicità non autorizzata."},
                    {"id": "Art. 1.4", "title": "Divieto di Simultaneità nelle Interruzioni", "text": "Al fine di eliminare alla radice ogni finestra temporale di interazione non sorvegliata, le fasi di non-attività (pause fisiologiche, break caffè, intervalli mensa) dei Contraenti devono essere rigorosamente scaglionate secondo una turnazione disgiunta. È fatta espressa proibizione di sospendere contemporaneamente le attività lavorative, prevenendo così la creazione di spazi di socializzazione non tracciata."},
                    {"id": "Art. 1.5", "title": "Divieto di Espressività Paratestuale", "text": "Le comunicazioni scritte (email, chat interne) devono limitarsi esclusivamente al contenuto denotativo e informativo, escludendo rigorosamente qualsiasi connotazione emotiva. È interdetto l'uso di marcatori grafici d'umore (emoji), formattazioni enfatiche (es. utilizzo del tutto maiuscolo) o punteggiatura iterata (es. punti esclamativi multipli) che possano generare ambiguità interpretativa sul tono del mittente o suggerire sottotesti non professionali."}
                ]
            },
            2: {
                "title": "PROTOCOLLO DI DISTANZIAMENTO FORMALE",
                "subtitle": "(Norme per l'implementazione di barriere fisiche e comportamentali anti-confidenza)",
                "clauses": [
                    {"id": "Art. 2.1", "title": "Divieto di Gratificazione Materiale (Policy Anti-Dono)", "text": "È fatto divieto assoluto di procedere allo scambio, alla dazione o all'offerta di beni, generi alimentari o favori materiali tra le Parti, indipendentemente dal valore economico. Tale comportamento viene riclassificato d'ufficio come 'Creazione di Debito Morale' e costituisce un potenziale innesco per dinamiche di reciprocità non contrattualizzate e lesive dell'autonomia professionale."},
                    {"id": "Art. 2.2", "title": "Disposizione Spaziale Non Adiacente", "text": "Nell'eventualità di condivisione del medesimo ufficio o ambiente 'open space', le postazioni di lavoro dei Contraenti devono essere tassativamente collocate secondo una geometria che impedisca il contatto visivo diretto e continuativo senza che vi sia una torsione volontaria del busto superiore ai 90 gradi, scoraggiando così l'interazione spontanea."},
                    {"id": "Art. 2.3", "title": "Regolamentazione del Supporto Vicario", "text": "Qualsiasi richiesta di supporto operativo, aiuto tecnico o sostituzione nelle mansioni tra i Soggetti deve essere obbligatoriamente formalizzata tramite l'apertura di un ticket digitale tracciabile. L'aiuto spontaneo non tracciato a sistema è vietato in quanto genera pericolosa ambiguità sulla titolarità delle responsabilità e sulla performance individuale."},
                    {"id": "Art. 2.4", "title": "Interdizione al Contatto Fisico (Zero-Touch Policy)", "text": "È abolito e proibito qualsiasi rituale di saluto o celebrazione che preveda il contatto epidermico (ivi incluse strette di mano, pacche sulla spalla o 'batti cinque'), indipendentemente dal contesto di successo o insuccesso lavorativo. Il contatto fisico è considerato un segnale di rischio immediato per l'integrità del distacco professionale."},
                    {"id": "Art. 2.5", "title": "Segregazione Spaziale Extra-Lavorativa", "text": "Ai Contraenti è fatto divieto di frequentare abitualmente i medesimi luoghi di aggregazione sociale o ricreativa al di fuori dell'orario contrattuale. L'eventuale coincidenza spaziale in orario extralavorativo deve essere tempestivamente segnalata all'App ALUA e rubricata come 'Incidente di Percorso' da non reiterare."}
                ]
            },
            3: {
                "title": "REGIME DI MEDIAZIONE OBBLIGATORIA",
                "subtitle": "(Protocollo di tracciamento totale e neutralizzazione della comunicazione diretta)",
                "clauses": [
                    {"id": "Art. 3.1", "title": "Obbligo di Tracciabilità Forense", "text": "Ogni interazione verbale avente oggetto decisionale, strategico o operativo deve essere immediatamente trascritta in un verbale sintetico e caricata sul server aziendale condiviso. Il principio 'Verba volant' è considerato una pratica di rischio non assicurabile; pertanto, nessuna decisione non scritta avrà valore esecutivo."},
                    {"id": "Art. 3.2", "title": "Depersonalizzazione del Feedback Valutativo", "text": "Le valutazioni, critiche o osservazioni sull'operato reciproco non possono essere espresse direttamente tra le Parti. Tali input devono essere inseriti in forma rigorosamente anonima nel sistema gestionale e saranno successivamente filtrati da un algoritmo di sintesi semantica incaricato di rimuovere qualsiasi carica emotiva o personale prima della notifica al destinatario."},
                    {"id": "Art. 3.3", "title": "Divieto di Accordo Bilaterale Autonomo", "text": "I Contraenti decadono dalla facoltà di prendere decisioni congiunte senza la previa ratifica di una terza parte (supervisore umano o validatore algoritmico). Qualsiasi accordo stipulato in solitudine tra i due soggetti è da considerarsi nullo e sanzionabile come tentativo di 'Complotto Relazionale' ai danni dell'organizzazione."},
                    {"id": "Art. 3.4", "title": "Limitazione Temporale del Contatto Visivo (Soglia Gottman)", "text": "Durante le riunioni operative strettamente necessarie, il contatto visivo diretto tra i Contraenti non può eccedere la durata di 15 (quindici) secondi consecutivi. Il superamento di tale soglia temporale attiva la presunzione automatica di sfida (dominanza gerarchica) o di complicità (collusione amicale), entrambe considerate nocive per l'equilibrio aziendale."},
                    {"id": "Art. 3.5", "title": "Inalienabilità delle Risorse Strumentali", "text": "È fatto divieto assoluto di utilizzo, prestito o scambio, anche temporaneo, delle risorse strumentali assegnate in dotazione esclusiva alla controparte (es. laptop, sedie, cancelleria, periferiche). Ogni violazione è classificata come 'Ingerenza Operativa Non Autorizzata', in quanto ostacola la corretta attribuzione dei dati di performance individuale e l'igiene della postazione."}
                ]
            },
            4: {
                "title": "STATO DI SEGREGAZIONE FUNZIONALE",
                "subtitle": "(Protocollo di massimo isolamento per l'inibizione fisica della collaborazione)",
                "clauses": [
                    {"id": "Art. 4.1", "title": "Adozione di Script Comunicativi Approvati", "text": "La comunicazione orale libera e spontanea è formalmente sospesa. I Contraenti sono autorizzati a interagire verbalmente solo ed esclusivamente utilizzando un frasario pre-approvato da ALUA ('Script a Bassa Entropia') limitato alle sole comunicazioni essenziali e binarie (es. 'Confermo ricezione', 'Richiedo dato X', 'Procedura completata')."},
                    {"id": "Art. 4.2", "title": "Congelamento Competitivo Alternato", "text": "Al fine di prevenire conflitti derivanti da invidia di status o competizione tossica, le Parti accettano il vincolo per cui non possano avvenire scatti di carriera, erogazione di bonus o riconoscimenti pubblici per entrambi i soggetti nel medesimo semestre fiscale. Il successo professionale di uno vincola automaticamente il congelamento dello status dell'altro."},
                    {"id": "Art. 4.3", "title": "Obbligo di Triangolazione dei Flussi (Divieto Peer-to-Peer)", "text": "È severamente vietato lo scambio diretto, fisico o digitale, di materiale, documenti o dati tra i Contraenti. Ogni flusso informativo deve essere obbligatoriamente mediato da un repository digitale neutro o da una terza figura garante (Proxy) che validi il passaggio, eliminando totalmente l'interazione diretta 'punto-a-punto' tra le Parti."},
                    {"id": "Art. 4.4", "title": "Isolamento Dipartimentale Coatto", "text": "L'Agenzia si riserva il diritto insindacabile (Potere di Veto Logistico) di imporre la dislocazione fisica immediata di uno dei Contraenti in un'altra sede, piano o ufficio, ovvero di imporre il regime di lavoro remoto (Smart Working) perpetuo, al fine di garantire la totale non-interazione fisica tra i soggetti a rischio."},
                    {"id": "Art. 4.5", "title": "Risoluzione Preventiva del Vincolo Contrattuale", "text": "In caso di persistenza dei valori di rischio critico nonostante le misure di segregazione, i Contraenti autorizzano preventivamente ALUA a inviare alla Direzione HR una raccomandazione vincolante di 'Impossibilità Sopravvenuta di Collaborazione', suggerendo il licenziamento per giusta causa o il trasferimento forzoso di uno dei soggetti per salvaguardare la produttività sistemica dell'azienda."}
                ]
            }
        }
    },
    "AMICALE": { 
        "header_suffix": "RELAZIONE AMICALE",
        "levels": {
            1: {
                "title": "PATTO DI LEALTÀ BASE",
                "subtitle": "Il minimo sindacale per la sussistenza del vincolo amicale: protocolli di puntualità, solvibilità e rispetto materiale.",
                "clauses": [
                    {"id": "Art. 1.1", "title": "Protocollo di Tolleranza Cronometrica e Sanzionamento del Ritardo", "text": "Negli appuntamenti, eventi sociali o incontri concordati bilateralmente, viene stabilita una franchigia di tolleranza temporale massima e non prorogabile pari a minuti 15 (quindici) rispetto all'orario fissato. Qualora il ritardo superi tale soglia temporale senza che sia pervenuta una comunicazione preventiva e giustificativa, la Parte in attesa matura il diritto all'annullamento unilaterale dell'incontro o, in alternativa, all'applicazione di una sanzione materiale compensativa (a titolo esemplificativo: saldo dell'intera consumazione o del titolo di ingresso a carico esclusivo del ritardatario)."},
                    {"id": "Art. 1.2", "title": "Regolamentazione della Solvibilità Immediata per Micro-Transazioni", "text": "Nell'eventualità di anticipo spese da parte di un Soggetto per conto dell'altro (biglietti cinema, cene condivise, servizi di trasporto), il rimborso del debito maturato deve avvenire entro un termine perentorio di 24 (ventiquattro) ore lavorative tramite bonifico istantaneo o pagamento digitale tracciabile. Qualsiasi impegno verbale generico di restituzione (\"poi ti do\") privo di data certa è considerato nullo e autorizza il creditore all'immediato sollecito formale."},
                    {"id": "Art. 1.3", "title": "Tracciabilità e Obbligo di Restituzione dei Beni in Comodato d'Uso", "text": "Il prestito temporaneo di materiale librario, capi di abbigliamento, accessori o oggetti personali è soggetto all'obbligo tassativo di restituzione nel medesimo stato di conservazione e funzionalità in cui il bene è stato ceduto, entro un termine massimo di 30 (trenta) giorni dalla consegna. È fatto espresso divieto di \"sub-prestito\" o cessione a terzi soggetti non autorizzati dal proprietario originale, pena l'immediata revoca della fiducia materiale."},
                    {"id": "Art. 1.4", "title": "Procedura di Annullamento Impegni e Penali per Cancellazione Tardiva", "text": "L'annullamento o la rinuncia a un impegno sociale congiunto deve essere comunicato alla controparte con un preavviso minimo di 12 (dodici) ore. La cancellazione \"last minute\" (inferiore alla soglia di preavviso), se priva di una causa di forza maggiore documentabile e oggettiva, è classificata come \"inadempienza organizzativa grave\" e impone alla Parte inadempiente l'onere logistico ed economico di ri-organizzare l'incontro a proprie spese."},
                    {"id": "Art. 1.5", "title": "Contingentamento della Messaggistica Vocale Asincrona", "text": "Al fine di tutelare le risorse cognitive e temporali della controparte, è vietato l'invio di note vocali di durata superiore ai 60 (sessanta) secondi (\"Soglia di Ascolto Sostenibile\"). I contenuti narrativi o logistici che richiedano tempi di esposizione superiori devono essere veicolati obbligatoriamente tramite chiamata telefonica sincrona o testo scritto dettagliato, per consentire una fruizione agevole."}
                ]
            },
            2: {
                "title": "PROTOCOLLO DI MANUTENZIONE PREVENTIVA",
                "subtitle": "Regole strutturali per impedire che lievi frizioni (economiche o comportamentali) evolvano in patologie relazionali.",
                "clauses": [
                    {"id": "Art. 2.1", "title": "Regolamentazione dello Scarico Emotivo e Verifica della Disponibilità Attentiva", "text": "Prima di sottoporre la controparte all'ascolto passivo di problematiche personali complesse, lamentele o sfoghi (\"Venting\"), il Soggetto emittente ha l'obbligo di verificare preventivamente la disponibilità delle risorse attentive ed emotive dell'altro. È fatto divieto assoluto di monopolizzare la conversazione con monologhi unilaterali qualora la controparte abbia manifestato, verbalmente o non verbalmente, segnali di saturazione, stanchezza o indisponibilità al supporto."},
                    {"id": "Art. 2.2", "title": "Divieto di Estensione Non Concordata della Partecipazione (Policy \"No +1\")", "text": "In riferimento agli eventi, cene o incontri pattuiti esplicitamente come \"esclusivi tra le Parti\", è fatto divieto di presentarsi accompagnati da partner sentimentali, familiari, colleghi o terzi amici non previsti, in assenza di una approvazione unanime preventiva e formale. L'alterazione arbitraria del numero o della tipologia dei partecipanti invalida l'impegno e autorizza l'annullamento dell'evento."},
                    {"id": "Art. 2.3", "title": "Divieto di Giudizio Retroattivo e Critica Non Costruttiva", "text": "È interdetto formulare critiche, sentenze morali o analisi \"col senno di poi\" su scelte passate della controparte che si sono rivelate fallimentari, qualora tali commenti non possiedano una chiara utilità costruttiva per il futuro. L'uso del fallimento altrui al solo scopo di ribadire la propria superiorità analitica o etica è considerato violazione del patto di supporto."},
                    {"id": "Art. 2.4", "title": "Vincolo di Segretezza e Non-Divulgazione (NDA Amicale)", "text": "Le informazioni classificate come \"Confidenziali\", \"Intime\" o \"Sensibili\" condivise durante l'interazione diretta sono coperte da vincolo di segretezza assoluta. È severamente vietato divulgare i dati personali dell'amico anche al proprio partner sentimentale, coniuge o familiare, salvo deroga specifica concessa per comprovato pericolo di vita o incolumità fisica."},
                    {"id": "Art. 2.5", "title": "Riconoscimento della Pluralità Relazionale e Rinuncia al Possesso", "text": "Ciascuna Parte riconosce e garantisce all'altra il pieno diritto di frequentare altri gruppi sociali, coltivare nuove amicizie o dedicarsi ad attività separate senza che ciò generi ritorsioni, gelosie o richieste di giustificazione. L'amicizia è definita come contratto non esclusivo; pertanto, sono vietate rivendicazioni di possesso sul tempo libero altrui o tentativi di monopolio relazionale."}
                ]
            },
            3: {
                "title": "REGIME DI FREQUENTAZIONE REGOLAMENTATA",
                "subtitle": "L'amicizia presenta criticità strutturali; si impongono regole rigide su frequenza e modalità di interazione per evitare il collasso.",
                "clauses": [
                    {"id": "Art. 3.1", "title": "Divieto di Ibridazione Forzata dei Gruppi Sociali Disomogenei", "text": "È fortemente sconsigliata, e soggetta a rigorosa valutazione di rischio, l'unione di cerchie sociali disomogenee (es. colleghi di lavoro e amici d'infanzia) in un unico evento senza un'adeguata verifica di compatibilità. Il promotore dell'evento si assume la responsabilità oggettiva (\"Promoter Liability\") per eventuali attriti, imbarazzi o disagi generati dall'interazione forzata tra gruppi estranei."},
                    {"id": "Art. 3.2", "title": "Divieto di Prestito Finanziario Informale e Regolamentazione del Credito", "text": "Qualsiasi prestito di denaro di importo superiore alla soglia di micro-transazione ordinaria deve essere tassativamente regolato da accordi scritti che definiscano tempi e modalità di restituzione. È vietato richiedere o concedere prestiti \"sulla fiducia\" che possano compromettere l'equilibrio del rapporto in caso di insolvenza o ritardo."},
                    {"id": "Art. 3.3", "title": "Interdizione alla Competizione Comparativa e Tutela dell'Autostima", "text": "È fatto divieto assoluto di istituire confronti diretti, competitivi o svalutanti tra i rispettivi traguardi professionali, status economici o successi sentimentali. Il successo o l'avanzamento di un Soggetto non deve essere mai interpretato, commentato o vissuto come una diminuzione del valore o del prestigio sociale dell'altro."},
                    {"id": "Art. 3.4", "title": "Obbligo di Riscontro Comunicativo Entro Termini Perentori", "text": "Anche in periodi di scarsa frequentazione o raffreddamento dei rapporti, le comunicazioni dirette che contengono domande specifiche o proposte logistiche devono ricevere un riscontro, affermativo o negativo, entro 48 (quarantotto) ore dalla ricezione. L'assenza di risposta prolungata (\"Ghosting parziale\") è classificata come negligenza comunicativa grave e lesiva della dignità altrui."},
                    {"id": "Art. 3.5", "title": "Divieto di Strumentalizzazione Professionale e Separazione Contabile", "text": "È fatto divieto di sfruttare il legame amicale per pretendere sconti, prestazioni lavorative gratuite, consulenze informali o corsie preferenziali legate alla professione della controparte. La sfera professionale e quella amicale devono rimanere contabilmente e proceduralmente separate; ogni prestazione lavorativa deve essere retribuita a prezzo di mercato o esplicitamente offerta come dono spontaneo."}
                ]
            },
            4: {
                "title": "STATO DI SOSPENSIONE AFFETTIVA",
                "subtitle": "L'amicizia è tecnicamente \"congelata\" o gestita come un obbligo formale per evitare la rottura definitiva. Si applica la legge marziale relazionale.",
                "clauses": [
                    {"id": "Art. 4.1", "title": "Obbligo di Calendarizzazione Formale e Sospensione della Spontaneità", "text": "Data la comprovata instabilità del rapporto, è sospesa ogni forma di frequentazione spontanea o improvvisata. Gli incontri possono avvenire esclusivamente previa pianificazione concordata con largo anticipo, definendo tassativamente luogo, orario e durata massima, al fine di evitare imprevisti che potrebbero generare conflitto."},
                    {"id": "Art. 4.2", "title": "Sterilizzazione degli Argomenti Divisivi e Protocollo di Sicurezza Conversazionale", "text": "Le Parti concordano l'interdizione tassativa di specifiche aree tematiche (politica, partner precedenti, finanze, o altri argomenti identificati come \"trigger\" di conflitto pregresso) durante le conversazioni. La violazione del divieto tematico, volontaria o accidentale, comporta l'immediata interruzione dell'incontro e l'allontanamento fisico delle Parti."},
                    {"id": "Art. 4.3", "title": "Razionamento Strategico della Frequenza di Contatto", "text": "Per prevenire la saturazione del rapporto, la dipendenza patologica o l'escalation del conflitto, viene imposto un limite massimo (\"Cap\") alla frequenza delle interazioni, siano esse telefoniche o fisiche. Il rispetto rigoroso degli intervalli di silenzio e distanza è condizione necessaria e vincolante per il mantenimento formale del vincolo."},
                    {"id": "Art. 4.4", "title": "Clausola di Neutralità in Caso di Conflitto con Terzi", "text": "Qualora una Parte sia coinvolta in un conflitto, contenzioso o rottura con soggetti terzi, l'altra Parte è tenuta al supporto emotivo discreto ma non all'azione ostile verso il terzo. È vietato richiedere la rottura di rapporti preesistenti con terzi o l'adozione di comportamenti bellicosi come \"prova di lealtà\" amicale."},
                    {"id": "Art. 4.5", "title": "Procedura di Dissoluzione Formale e Liquidazione del Rapporto", "text": "Nell'ipotesi di rottura definitiva del legame (Rischio Critico irreversibile), le Parti si impegnano a comunicare la cessazione del rapporto in modo esplicito e verbale, evitando la sparizione silenziosa (\"Ghosting\"). Si procederà contestualmente alla restituzione di tutti i beni in comodato ancora detenuti e alla definizione tombale delle eventuali pendenze economiche residue."}
                ]
            }
        }
    },
    "ROMANTICA": { 
        "header_suffix": "RELAZIONE ROMANTICA",
        "intro_text": "ARTICOLO SPECIALE – CLAUSOLA DI ESCLUSIVITÀ E DEFINIZIONE DI TRADIMENTO\n(Protocollo per la definizione del perimetro di fedeltà e sanzionamento delle violazioni)\nNota: Le Parti sono tenute a selezionare una delle seguenti Opzioni come vincolo contrattuale attivo.\n\nOpzione A: Modello di Relazione Chiusa (Monogamia Contrattuale)\nQualora i Contraenti abbiano optato per un regime di esclusività affettivo-sessuale assoluta, la fattispecie di \"Tradimento\" si perfeziona con l'instaurazione di un legame affettivo, romantico o l'effettuazione di atti sessuali e di intimità fisica di qualsiasi grado con un soggetto terzo esterno al binomio. Tale condotta è giuridicamente qualificata come violazione sostanziale, irreversibile e ingiustificabile della clausola di esclusività e determina l’immediata attivazione della massima penale risarcitoria a carico della Parte inadempiente, oltre alla decadenza fiduciaria.\n\nOpzione B: Modello di Relazione Aperta (Non-Monogamia Consensuale)\nQualora i Contraenti abbiano optato per un regime di non-monogamia consensuale, il Tradimento non è definito dall'atto fisico o affettivo esterno in sé, bensì dalla violazione dei \"Protocolli di Condotta e Comunicazione\" concordati. Costituiscono violazione contrattuale grave: l'occultamento intenzionale di incontri; l'omissione di informazioni sanitarie essenziali; il superamento dei limiti emotivi o logistici pattuiti. La violazione di tali protocolli configura la fattispecie di \"Slealtà Comunicativa\" e comporta l’attivazione della massima penale risarcitoria.\n\nOpzione C: Modello Poliamoroso Gerarchico (Poligamia Etica Strutturata)\nIn regime di Poliamore Gerarchico, si stabilisce l'esistenza di un \"Vincolo Primario\" (il presente contratto) che detiene priorità assoluta nell'allocazione delle risorse (tempo, finanze, progettualità) rispetto ai \"Vincoli Secondari\". Il Tradimento si configura qualora una Parte: elevi arbitrariamente una relazione secondaria equiparandola alla primaria (\"Drottamento di Risorse\"); violi il potere di veto del partner primario; occulti l'esistenza di nuovi partner (violazione del consenso informato). Tale condotta è classificata come \"Sovversione della Gerarchia Pattuita\" e sanzionabile con la massima penale.\n\nOpzione D: Modello a Esclusività Emotiva (Apertura Ricreativa/Swinging)\nIn regime di distinzione funzionale, è concessa facoltà di intrattenere rapporti sessuali con terzi, purché limitati alla sfera \"Ludico-Motoria\" e privi di coinvolgimento sentimentale. Il Tradimento è definito come \"Infedeltà Emotiva\" e si concretizza in: sviluppo di attaccamento romantico o dipendenza affettiva; reiterazione degli incontri con il medesimo soggetto oltre la soglia di sicurezza (\"Regola One-Night Only\"); condivisione di attività di intimità non sessuale. La violazione della clausola di asetticità sentimentale comporta l’attivazione della massima penale risarcitoria.",
        # Struttura "levels" per clausole specifiche graduate per rischio, oltre all'intro
        "levels": {
            1: {
                "title": "LOGISTICA DOMESTICA E MICRO-CONFLITTUALITÀ",
                "subtitle": "(Violazioni attinenti alla gestione pratica della convivenza o della frequentazione)",
                "clauses": [
                    {"id": "Art. 1.1", "title": "Divieto di Fruizione Multimediale Asincrona (Serie TV)", "text": "Nel caso di prodotti audiovisivi seriali o contenuti narrativi la cui fruizione sia stata iniziata congiuntamente (\"Serie di Coppia\"), è fatto divieto assoluto e tassativo di procedere alla visione unilaterale di nuovi episodi o segmenti in assenza della controparte. La violazione configura il reato di \"Spoiler Contrattuale\" e \"Abbandono Narrativo\"."},
                    {"id": "Art. 1.2", "title": "Divieto di Istruzione alla Guida Non Richiesta (Backseat Driving)", "text": "Qualora i Contraenti si trovino all'interno di un veicolo condotto da una delle Parti, è fatto divieto al passeggero di fornire istruzioni, suggerimenti o critiche non richieste riguardanti l'itinerario, la velocità di crociera o le manovre, salvo i casi di imminente pericolo di vita o collisione certa."},
                    {"id": "Art. 1.3", "title": "Gestione dell'Immagine Digitale Congiunta", "text": "La pubblicazione su piattaforme social, pubbliche o private, di materiale fotografico o video ritraente la coppia è subordinata all'approvazione estetica e contenutistica preventiva di entrambe le Parti (diritto di veto sull'immagine). La pubblicazione unilaterale di scatti in cui la controparte risulti non valorizzata è considerata atto ostile."},
                    {"id": "Art. 1.4", "title": "Protocollo di Contenimento dell'Entropia Domestica", "text": "È fatto obbligo a ciascun Contraente di limitare la dispersione di effetti personali, indumenti o documentazione sulle superfici comuni al di fuori degli spazi di stoccaggio preposti. Gli oggetti depositati in via transitoria nelle \"Aree di Vita Comune\" devono essere rimossi o ricollocati entro un termine perentorio di 12 (dodici) ore, pena lo smaltimento coatto."},
                    {"id": "Art. 1.5", "title": "Divieto di Passività Decisionale", "text": "Qualora un Contraente declini l'esercizio del proprio potere decisionale in merito a scelte congiunte (cena, svago, logistica), dichiarando neutralità (\"Fai tu\"), decade automaticamente dal diritto di critica o veto sulla soluzione adottata dalla controparte. È altresì vietato respingere una proposta senza contestualmente presentare almeno un'alternativa concreta e praticabile."}
                ]
            },
            2: {
                "title": "GESTIONE SOCIALE E SPAZI INDIVIDUALI",
                "subtitle": "(Violazioni che impattano sull'autonomia personale e sull'interazione esterna)",
                "clauses": [
                    {"id": "Art. 2.1", "title": "Filtro delle Ingerenze Genitoriali", "text": "Ciascun Contraente si impegna contrattualmente a gestire in via esclusiva e diretta le intromissioni della propria famiglia di origine, garantendo alla controparte lo scudo protettivo (\"Buffer Zone\") da critiche, consigli non richiesti o presenze invasive di suoceri e affini."},
                    {"id": "Art. 2.2", "title": "Diritto al Distacco Individuale", "text": "È formalmente riconosciuto a ciascuna Parte il diritto inalienabile a periodi di isolamento volontario o attività individuale (hobby, uscite autonome) senza che ciò comporti per la controparte diritto di ritorsione, manifestazioni di gelosia o richieste di giustificazione dettagliata."},
                    {"id": "Art. 2.3", "title": "Regolamentazione delle Scenate in Pubblico", "text": "Eventuali divergenze, conflitti o malumori insorti in luoghi pubblici o in presenza di terzi devono essere rigorosamente differiti e discussi al rientro in sede privata. È vietato l'innesco di litigi, musi lunghi o l'uso di toni alterati in contesto sociale, al fine di preservare il decoro della coppia."},
                    {"id": "Art. 2.4", "title": "Divieto di Comparazione Competitiva", "text": "È fatto divieto assoluto a ciascuna Parte di istituire confronti, diretti o allusivi, tra la condotta, lo status economico o le prestazioni della controparte e quelle riferibili a partner di soggetti terzi. Tale divieto include riferimenti alla capacità di spesa, alla frequenza di gesti romantici altrui o l'uso di modelli social (Instagram/TikTok) come standard per indurre senso di inadeguatezza."},
                    {"id": "Art. 2.5", "title": "Divieto di Sollecitazione Oltre Soglia (Nagging)", "text": "Al fine di preservare l'igiene comunicativa, ciascun Contraente si impegna a non reiterare una medesima richiesta operativa per un numero di volte superiore a 3 (tre), una volta che tale richiesta sia stata recepita. Il superamento di tale soglia numerica è catalogato come \"Interferenza Comunicativa Cronica\" e costituisce violazione contrattuale autonoma."}
                ]
            },
            3: {
                "title": "FIDUCIA, RISPETTO E PASSATO",
                "subtitle": "(Violazioni che intaccano la sicurezza emotiva e la lealtà)",
                "clauses": [
                    {"id": "Art. 3.1", "title": "Regolamentazione della Memoria Storico-Affettiva", "text": "È fatto divieto tassativo di evocare figure sentimentali del passato (\"Ex\") qualora tale menzione configuri una comparazione competitiva, un'espressione di nostalgia idealizzante o una provocazione strategica volta a suscitare gelosia. La condivisione del vissuto pregresso è legittima esclusivamente se finalizzata alla crescita della consapevolezza di coppia e priva di intento manipolatorio."},
                    {"id": "Art. 3.2", "title": "Inviolabilità della Corrispondenza e dei Dispositivi", "text": "È tassativamente vietato l'accesso, la lettura o il monitoraggio dei dispositivi personali (smartphone, account social) della controparte. Tale divieto è derogabile esclusivamente previa esplicita autorizzazione verbale o sblocco biometrico volontario fornito dal titolare contestualmente alla richiesta. L'autorizzazione si intende limitata alla singola sessione e alla specifica finalità dichiarata."},
                    {"id": "Art. 3.3", "title": "Divieto di Accusa Infondata e Onere della Prova", "text": "Qualsiasi contestazione inerente la presunta infedeltà o condotta inappropriata deve essere fondata su elementi probatori oggettivi. Sono tassativamente inammissibili le accuse basate su \"Illeciti Onirici\" (tradimenti sognati), \"Processi alle Intenzioni\" (intuizioni prive di riscontro) o \"Interazioni Sociali Neutre\" prive di connotazione seduttiva."},
                    {"id": "Art. 3.4", "title": "Divieto di Ridicolizzazione Pubblica e Abuso di Confidenza", "text": "È tassativamente vietato utilizzare fragilità, fobie o episodi privati imbarazzanti comunicati dalla controparte in regime di intimità, quale materiale per intrattenimento sociale o aneddoti goliardici in presenza di terzi. La protezione della dignità sociale della controparte costituisce obbligo contrattuale essenziale."},
                    {"id": "Art. 3.5", "title": "Divieto di Strumentalizzazione dell'Intimità", "text": "È fatto divieto assoluto di utilizzare l'intimità sessuale, sia nella forma della negazione punitiva (\"Weaponized Withholding\") sia in quella della concessione premiale, come merce di scambio negoziale per ottenere vantaggi in altre aree della gestione di coppia."}
                ]
            },
            4: {
                "title": "INTEGRITÀ EMOTIVA E FONDAMENTA DEL RAPPORTO",
                "subtitle": "(Violazioni gravi che compromettono la stabilità della relazione)",
                "clauses": [
                    {"id": "Art. 4.1", "title": "Divieto di Minaccia Risolutiva e Ricatto Strategico", "text": "È fatto divieto assoluto di utilizzare, durante i conflitti, qualsiasi forma di minaccia atta a destabilizzare l'integrità del rapporto. Tale divieto include la \"Minaccia Risolutiva\" (evocare la rottura come tattica), la \"Minaccia Estorsiva\" (condizionare l'affetto all'obbedienza) e la \"Minaccia di Autolesionismo\". La violazione è considerata \"Atto di Vessazione Strategica\"."},
                    {"id": "Art. 4.2", "title": "Prescrizione delle Divergenze Pregresse", "text": "È inammissibile l'utilizzo di errori, tradimenti o mancanze commesse dalla controparte e già esplicitamente perdonati, sanzionati o archiviati in passato, come argomentazione valida in nuovi conflitti. Tali eventi sono coperti da prescrizione emotiva tombale."},
                    {"id": "Art. 4.3", "title": "Proibizione del Disprezzo Personale (Ad Hominem)", "text": "Nel corso delle dispute, la critica deve limitarsi rigorosamente al comportamento o all'azione specifica oggetto del contendere. È fatto divieto assoluto di attaccare la persona, l'intelligenza o l'aspetto fisico della controparte con epiteti ingiuriosi, sarcasmo denigratorio o disprezzo manifesto."},
                    {"id": "Art. 4.4", "title": "Divieto di Distorsione della Realtà Percettiva (Gaslighting)", "text": "È vietata ogni condotta verbale o comportamentale volta a negare la realtà fattuale degli eventi o a mettere in dubbio la sanità mentale e la stabilità mnemonica della controparte (es. \"Ti stai inventando tutto\"), al fine di manipolare la percezione della realtà a proprio vantaggio difensivo."},
                    {"id": "Art. 4.5", "title": "Divieto di Ultimatum Coercitivo", "text": "È fatto divieto di porre la controparte di fronte a scelte binarie forzate (\"Aut aut\") che implichino il sacrificio di valori fondamentali, relazioni familiari pregresse o aspirazioni professionali legittime come condizione necessaria (\"Conditio sine qua non\") per la prosecuzione del rapporto contrattuale."}
                ]
            }
        }
    },
    "FAMILIARE": { 
        "header_suffix": "RELAZIONE FAMILIARE",
        "levels": {
            1: {
                "title": "LOGISTICA E GALATEO MATERIALE",
                "subtitle": "Normativa quadro per la gestione delle violazioni pratiche e della scortesia sociale",
                "clauses": [
                    {"id": "Art. 1.1", "title": "Protocollo di Puntualità agli Eventi Congiunti", "text": "Negli appuntamenti concordati bilateralmente, è ammessa una tolleranza temporale massima e perentoria di 15 (quindici) minuti rispetto all'orario prefissato. Il superamento di tale soglia, in assenza di comunicazione tempestiva e giustificata, conferisce alla Parte in attesa la piena facoltà di procedere all'annullamento unilaterale dell'incontro, restando esente da qualsiasi sanzione morale, recriminazione o obbligo di giustificazione successiva."},
                    {"id": "Art. 1.2", "title": "Regolamentazione del Comodato di Beni Mobili", "text": "È fatto divieto assoluto a ciascuna Parte di procedere al prelievo, all'utilizzo o all'appropriazione temporanea di oggetti, indumenti, accessori o beni mobili di proprietà esclusiva della controparte in assenza di un'autorizzazione esplicita e preventiva. Il bene oggetto di prestito deve essere tassativamente restituito nel medesimo stato di conservazione e funzionalità (\"Status Quo Ante\") in cui è stato ceduto, pena il risarcimento del danno."},
                    {"id": "Art. 1.3", "title": "Veto sulle Scelte Alimentari e Dietetiche", "text": "Durante i momenti di convivialità o condivisione dei pasti, è interdetta a ciascuna Parte la formulazione di qualsiasi commento, giudizio o osservazione in merito alla quantità o qualità del cibo ingerito dalla controparte. Tale divieto si estende, senza eccezioni, a critiche riguardanti regimi dietetici specifici, intolleranze alimentari o scelte etiche di consumo, tutelando la piena autonomia nutrizionale del soggetto."},
                    {"id": "Art. 1.4", "title": "Gestione e Tutela dell'Immagine Digitale", "text": "È severamente interdetta la pubblicazione, diffusione o condivisione sui social network di immagini, video o contenuti multimediali ritraenti la controparte, nonché l'azione di associazione nominale (\"tagging\"), in assenza di preventivo e inequivocabile consenso scritto o verbale. Su semplice richiesta della Parte interessata, la controparte è obbligata contrattualmente alla rimozione immediata e definitiva del contenuto oggetto di contestazione."},
                    {"id": "Art. 1.5", "title": "Definizione dei Parametri di Urgenza", "text": "L'utilizzo di canali di comunicazione ad alta priorità (chiamate telefoniche ripetute, messaggistica con notifiche di emergenza) o l'attivazione di contatti in orari notturni è riservato esclusivamente a situazioni di comprovata e oggettiva gravità (a titolo esemplificativo: ospedalizzazioni, sinistri gravi, decessi). È fatto divieto di qualificare come \"urgenti\" necessità di ordine logistico ordinario o sfoghi emotivi estemporanei, che dovranno seguire i canali ordinari."}
                ]
            },
            2: {
                "title": "INGERENZA SOCIALE E AUTONOMIA",
                "subtitle": "Protocollo contro la limitazione della libertà di scelta e il giudizio sullo stile di vita",
                "clauses": [
                    {"id": "Art. 2.1", "title": "Inibizione della Consulenza Non Sollecitata", "text": "È reciprocamente inibita l'erogazione di pareri, suggerimenti, critiche costruttive o direttive comportamentali in merito alla gestione della carriera professionale, dell'organizzazione domestica o delle scelte estetiche della controparte, qualora manchi una preventiva, formale ed esplicita richiesta di consulenza (\"Solicited Advice\"). Ogni violazione è classificata come ingerenza indebita nella sfera di autodeterminazione."},
                    {"id": "Art. 2.2", "title": "Protocollo di Astensione dal Giudizio Estetico", "text": "È proibito formulare commenti valutativi, indipendentemente dall'intento critico o apparentemente elogiativo (complimenti non richiesti), riguardanti le variazioni ponderali, lo stile di abbigliamento, l'acconciatura o l'aspetto fisico generale della controparte. Il corpo del soggetto è dichiarato \"Zona Franca\" da qualsiasi sindacato esterno."},
                    {"id": "Art. 2.3", "title": "Obbligo di Neutralità nelle Ricorrenze", "text": "La pianificazione logistica delle festività comandate o delle ricorrenze tradizionali non costituisce vincolo automatico di presenza. Il rifiuto di una Parte di partecipare a eventi collettivi o riunioni familiari è legittimo e non sanzionabile dalla controparte mediante ritorsioni emotive, induzione di senso di colpa o pratiche di ostracismo sociale."},
                    {"id": "Art. 2.4", "title": "Divieto di Comparazione Competitiva (Benchmarking Familiare)", "text": "È fatto divieto assoluto a ciascuna Parte di istituire confronti qualitativi, quantitativi o di status tra la controparte e terzi soggetti (ivi inclusi consanguinei, fratelli, cugini o conoscenti), finalizzati a evidenziare presunte carenze prestazionali, economiche o sociali della stessa. Tale pratica è riconosciuta come lesiva della dignità individuale."},
                    {"id": "Art. 2.5", "title": "Divieto di Inquisizione Sentimentale", "text": "È fatto divieto a ciascun Contraente di sottoporre alla controparte interrogazioni, dirette o indirette, sondaggi o allusioni inerenti lo stato delle relazioni affettive, la situazione sentimentale o la sfera sessuale, salvo esplicita, spontanea e volontaria dichiarazione della Parte interessata (\"Disclosure Spontanea\")."}
                ]
            },
            3: {
                "title": "VIOLAZIONE DELLA PRIVACY E DELLA FIDUCIA",
                "subtitle": "Norme a tutela del patto di lealtà e della sicurezza delle informazioni personali",
                "clauses": [
                    {"id": "Art. 3.1", "title": "Riservatezza Finanziaria e Patrimoniale", "text": "Nessun Contraente ha facoltà di richiedere alla controparte informazioni di dettaglio, estratti conto o giustificativi in merito a reddito percepito, consistenza dei risparmi o scelte di investimento, né di sindacare le relative modalità di spesa o allocazione delle risorse, fatti salvi gli obblighi di legge o accordi di condivisione spese precedentemente stipulati."},
                    {"id": "Art. 3.2", "title": "Divieto di Triangolazione del Conflitto", "text": "In caso di controversia o divergenza tra i Contraenti, è fatto divieto assoluto di coinvolgere terze parti appartenenti al nucleo familiare allargato (es. genitori, suoceri, fratelli comuni) nel tentativo di ottenere mediazione non richiesta, supporto morale fazioso o la costituzione di alleanze strategiche contro l'altra Parte. Il conflitto deve rimanere circoscritto ai diretti interessati."},
                    {"id": "Art. 3.3", "title": "Divieto di Divulgazione a Terzi (Gossip Familiare)", "text": "Le informazioni confidenziali, i segreti o i dettagli sensibili appresi durante le interazioni dirette e fiduciarie non possono essere divulgati, trasmessi o palesati ad altri membri del nucleo parentale allargato o a soggetti terzi in assenza di esplicito consenso scritto della Parte interessata."},
                    {"id": "Art. 3.4", "title": "Clausola di Non-Ingerenza Coniugale", "text": "I Contraenti si impegnano ad astenersi reciprocamente da qualsiasi commento, critica, analisi non richiesta o intromissione riguardante il partner ufficiale, coniuge o compagno dell'altra Parte. Ogni divergenza o dinamica relazionale deve essere gestita esclusivamente all'interno della coppia di riferimento, senza interferenze esterne."},
                    {"id": "Art. 3.5", "title": "Inviolabilità della Corrispondenza e dei Dispositivi", "text": "È fatto divieto assoluto di ispezionare, consultare, sbloccare o leggere, anche casualmente, i dispositivi elettronici (smartphone, tablet, PC), la corrispondenza cartacea o gli effetti personali (borse, portafogli) della controparte lasciati incustoditi negli spazi comuni o privati, nel pieno rispetto del diritto costituzionale alla segretezza delle comunicazioni."}
                ]
            },
            4: {
                "title": "INTEGRITÀ PSICOLOGICA E ABUSO EMOTIVO",
                "subtitle": "Sanzioni contro comportamenti tossici, manipolatori o abusanti",
                "clauses": [
                    {"id": "Art. 4.1", "title": "Preclusione alla Recriminazione Storica (Prescrizione)", "text": "Le Parti concordano l'improcedibilità e l'inammissibilità di qualsivoglia argomentazione fondata su contenziosi, torti, errori o inadempienze verificatisi in epoca antecedente ai 24 (ventiquattro) mesi dalla data odierna. Tali eventi sono considerati \"prescritti\" e non possono essere utilizzati come arma dialettica nel presente."},
                    {"id": "Art. 4.2", "title": "Diritto di Veto sugli Argomenti Sensibili (Safe Words)", "text": "Ciascuna Parte ha facoltà insindacabile di dichiarare specifici argomenti (quali, a titolo esemplificativo: politica, religione, traumi pregressi, scelte riproduttive) come \"Zone Interdette\". L'attivazione di tali argomenti da parte della controparte comporta il diritto all'immediata interruzione dell'interazione verbale e all'allontanamento fisico senza preavviso."},
                    {"id": "Art. 4.3", "title": "Divieto di Ostruzionismo Comunicativo (Silent Treatment)", "text": "È fatto divieto di utilizzare il silenzio prolungato, il rifiuto sistematico di rispondere alle chiamate o l'interruzione unilaterale e punitiva dei canali comunicativi come strumento ritorsivo a seguito di un disaccordo. Tale condotta è classificata come abuso emotivo passivo-aggressivo."},
                    {"id": "Art. 4.4", "title": "Divieto di Manipolazione Emotiva e Vittimizzazione", "text": "È vietato l'utilizzo di condotte verbali o non verbali volte a indurre senso di colpa nella controparte al fine di ottenere adempimenti non dovuti o concessioni. Tale divieto include esplicitamente l'uso strumentale di riferimenti al proprio stato di salute precario o all'anzianità anagrafica quali leve negoziali coercitive."},
                    {"id": "Art. 4.5", "title": "Divieto di Distorsione della Realtà Percettiva (Gaslighting)", "text": "È fatto divieto assoluto a ciascun Contraente di porre in essere condotte verbali o comportamentali volte a negare sistematicamente la realtà fattuale di eventi accaduti, ovvero a mettere in dubbio la stabilità mnemonica, la capacità di giudizio o la sanità mentale della controparte, al fine di delegittimarne il vissuto emotivo o eludere le proprie responsabilità contrattuali e morali."}
                ]
            }
        }
    },
    "CIRCOSTANZIALE": { 
        "header_suffix": "RELAZIONE CIRCOSTANZIALE",
        "levels": {
            1: {
                "title": "PROTOCOLLO DI CORTESIA CIVILE",
                "subtitle": "Normativa quadro per il riconoscimento e il saluto in sicurezza",
                "clauses": [
                    {"id": "Art. 1.1", "title": "Protocollo di Identificazione Nominale", "text": "Viene sancito l'obbligo inderogabile per i Soggetti contraenti, all'atto di un incontro fortuito o non calendarizzato, di procedere alla reciproca e immediata conferma della propria identità anagrafica. Qualora una delle Parti abbia subito una rimozione mnemonica, temporanea o permanente, relativa al nominativo della controparte, la stessa è formalmente autorizzata a fare ricorso a una formula allocutiva impersonale standardizzata (a titolo esemplificativo: \"Salve\", \"Ehilà\"), esonerandola da qualsiasi sanzione sociale. Vige tuttavia il divieto assoluto di tentare la ricostruzione dell'identità basandosi su frammenti mnemonici parziali o inferenze probabilistiche, al fine di evitare l'imbarazzo derivante da un'errata attribuzione."},
                    {"id": "Art. 1.2", "title": "Perimetro di Sicurezza Conversazionale", "text": "Le interazioni verbali tra le Parti dovranno rigorosamente attenersi a fatti oggettivi, empiricamente verificabili e privi di potenziale controversia. Il \"Perimetro Tematico Neutro\" ammette esclusivamente scambi verbali riguardanti la logistica urbana, le variabili meteorologiche correnti o osservazioni asettiche sull'ambiente circostante immediato. Sono tassativamente esclusi, e pertanto sanzionabili come violazione contrattuale, argomenti ritenuti polarizzanti quali orientamenti politici, credo religiosi o bollettini medici relativi allo stato di salute personale o di terzi."},
                    {"id": "Art. 1.3", "title": "Codifica del Cerimoniale di Saluto", "text": "Le modalità di saluto sono strettamente codificate e limitate a un'inclinazione del capo o a un breve saluto verbale distale. La stretta di mano è tollerata esclusivamente in contesti che richiedano una presentazione formale a soggetti terzi. Qualsiasi forma di contatto fisico ulteriore, inclusi baci sulla guancia, abbracci o pacche sulle spalle, è severamente vietata e sarà classificata d'ufficio come \"Ingerenza Corporea Non Contrattualizzata\"."},
                    {"id": "Art. 1.4", "title": "Facoltà di Recesso Unilaterale dall’Interazione", "text": "In circostanze di incontro casuale in luogo pubblico o aperto al pubblico, è riconosciuto a ciascuna delle Parti il diritto insindacabile di interrompere la conversazione in qualsiasi istante. Tale recesso può essere esercitato adducendo la formula generica di \"Vincoli Temporali Pregressi\", senza l'onere di fornire prove o giustificazioni dettagliate. La controparte è contrattualmente obbligata a prendere atto del congedo con effetto immediato, astenendosi da qualsiasi tentativo di trattenimento o negoziazione del tempo residuo."},
                    {"id": "Art. 1.5", "title": "Periodo di Moratoria Digitale", "text": "È fatto divieto assoluto di inviare, trasmettere o sollecitare richieste di collegamento (amicizia, following) sui profili social network personali prima che sia decorso un periodo di raffreddamento (Cooling-off Period) non inferiore alle 48 (quarantotto) ore dal primo incontro fisico. L'eventuale aggiunta istantanea è classificata come \"Violazione della Privacy Preventiva\" e autorizza il blocco unilaterale da parte del ricevente."}
                ]
            },
            2: {
                "title": "LIVELLO DI INTERAZIONE SUPERFICIALE",
                "subtitle": "Regolamento per il mantenimento della sicurezza conversazionale e prossemica",
                "clauses": [
                    {"id": "Art. 2.1", "title": "Protocollo di Distanziamento Prossemico", "text": "Durante l'intera durata dell'interazione fisica, i Soggetti sono tenuti a rispettare tassativamente una distanza prossemica di sicurezza non inferiore a centimetri 100 (cento). È fatto espresso divieto di invadere lo spazio aereo personale della controparte o di esercitare contatti fisici, anche se accidentali o intesi come gesti enfatici (es. toccare l'avambraccio o la spalla), al fine di preservare l'integrità dello spazio vitale individuale."},
                    {"id": "Art. 2.2", "title": "Proibizione di Divulgazione Biografica Non Sollecitata", "text": "È interdetto a ciascuna Parte condividere, narrare o esporre dettagli intimi, traumatici o eccessivamente personali della propria esistenza, salvo il caso in cui tali informazioni siano state esplicitamente richieste dalla controparte mediante domanda diretta e inequivocabile. L'esposizione non richiesta del proprio vissuto emotivo (Over-sharing) è considerata una violazione sostanziale del contratto sociale di superficialità vigente tra le Parti."},
                    {"id": "Art. 2.3", "title": "Obbligo di Trasparenza nelle Intenzioni", "text": "Nel caso in cui una delle Parti intenda proporre un incontro successivo, è fatto obbligo di dichiararne contestualmente la natura teleologica (Professionale o Ludica). L'utilizzo di formule vaghe o ambivalenti nella formulazione dell'invito è severamente vietato, al fine di prevenire qualsiasi disallineamento sulle aspettative relazionali o fraintendimenti sulle finalità dell'incontro stesso."},
                    {"id": "Art. 2.4", "title": "Interdizione alla Procrastinazione Illusoria", "text": "È fatto divieto di utilizzare formule di chiusura o congedo che implichino un impegno futuro (a titolo esemplificativo: \"Ci vediamo presto\", \"Dobbiamo sentirci\") qualora non vi sia la reale e concreta intenzione di procedere. In assenza di una data calendarizzata entro le successive 24 ore, tali frasi saranno considerate \"Falsità Cerimoniali Sanzionabili\" per violazione della buona fede."},
                    {"id": "Art. 2.5", "title": "Tutela dell'Invisibilità Digitale", "text": "Vige il divieto assoluto di documentare l'incontro tramite l'acquisizione di fotografie, video o registrazioni effimere (\"Stories\") senza previa liberatoria esplicita e verbale. La mera coincidenza spaziale della controparte nello stesso luogo fisico non costituisce autorizzazione tacita alla sua inclusione nella narrazione digitale dell'altro contraente."}
                ]
            },
            3: {
                "title": "REGIME DI DISTACCO PREVENTIVO",
                "subtitle": "Norme limitative per il contenimento dell'approfondimento relazionale",
                "clauses": [
                    {"id": "Art. 3.1", "title": "Regime di Separazione Contabile Analitica", "text": "In caso di consumazione congiunta di beni o servizi, il saldo economico deve avvenire rigorosamente in modalità separata per singola voce di spesa. È fatto espresso divieto di offrire la consumazione alla controparte o di proporre divisioni forfettarie del conto, al fine di prevenire l'instaurarsi di obbligazioni morali, debiti di riconoscenza o asimmetrie relazionali."},
                    {"id": "Art. 3.2", "title": "Informativa Preliminare verso Terzi", "text": "Prima di procedere all'introduzione della controparte a soggetti terzi appartenenti al proprio cerchio sociale consolidato, il proponente ha l'obbligo di fornire ai suddetti terzi un quadro sintetico (Briefing) della natura della relazione. È vietato esporre il mero conoscente a dinamiche di gruppo complesse o pregresse senza adeguato preavviso, evitando così il fenomeno di disagio sociale noto come \"Effetto Pesce fuor d'acqua\"."},
                    {"id": "Art. 3.3", "title": "Divieto di Indagine Storica Retroattiva (Deep Liking)", "text": "È severamente vietato interagire, tramite reazioni o commenti, con i contenuti social della controparte pubblicati in data antecedente all'inizio della conoscenza diretta. Tale pratica è classificata come attività di indagine archeologica non autorizzata sul passato del soggetto e costituisce una violazione della privacy cronologica."},
                    {"id": "Art. 3.4", "title": "Principio di Letteralità del Diniego", "text": "Qualora una Parte declini un invito o un'opportunità di contatto, il rifiuto deve essere inteso nella sua accezione semantica più letterale, definitiva e inappellabile. È fatto divieto di interpretare la negazione come una strategia negoziale inversa o come una tacita richiesta di maggiore insistenza o corteggiamento."},
                    {"id": "Art. 3.5", "title": "Proibizione di Omaggi e Dazioni Materiali", "text": "È fatto divieto assoluto di elargire regali, souvenir, pensieri materiali o beni, indipendentemente dal loro valore economico. Il dono scambiato tra semplici conoscenti è considerato un'indebita invasione della sfera privata che forza il ricevente a una reciprocità non richiesta e non contrattualizzata."}
                ]
            },
            4: {
                "title": "STATO DI IRRILEVANZA RECIPROCA",
                "subtitle": "Protocollo per la gestione dell'estraneità formale e sostanziale",
                "clauses": [
                    {"id": "Art. 4.1", "title": "Inibizione dell'Approccio Verbale Spontaneo", "text": "I Soggetti non sono autorizzati ad attivare canali comunicativi verbali se non per comprovata emergenza vitale o necessità logistica immediata e improrogabile. In caso di compresenza fortuita nello stesso luogo fisico, le Parti sono tenute ad applicare il protocollo di \"Inattenzione Civile Selettiva\" (ignorarsi reciprocamente mantenendo un contegno educato)."},
                    {"id": "Art. 4.2", "title": "Segregazione dei Livelli di Privacy Digitale", "text": "Le Parti hanno l'obbligo contrattuale di configurare i propri profili social in modo restrittivo, impedendo alla controparte l'accesso a contenuti classificati come \"Intimi\", \"Privati\" o riservati a liste di distribuzione privilegiata (es. \"Amici Stretti\"), mantenendo l'interazione, se presente, esclusivamente sui canali pubblici."},
                    {"id": "Art. 4.3", "title": "Turnazione Temporale negli Spazi Pubblici", "text": "In caso di frequentazione abituale e sovrapposta dei medesimi locali, servizi o spazi pubblici, ALUA raccomanda e incentiva l'adozione volontaria di uno scaglionamento temporale (fasce orarie differenziate), al fine di evitare la sovrapposizione fisica costante che potrebbe generare attrito, imbarazzo o necessità di interazione forzata."},
                    {"id": "Art. 4.4", "title": "Divieto di Divulgazione a Terzi (Protocollo Anti-Gossip)", "text": "È fatto divieto assoluto di discutere, commentare, diffondere o disseminare informazioni riguardanti la controparte con soggetti terzi. Data la natura effimera e superficiale del vincolo, qualsiasi trasmissione di dati personali è considerata una violazione della riservatezza non giustificata da alcun interesse pubblico o privato."},
                    {"id": "Art. 4.5", "title": "Patto di Reciproca Indifferenza (Decadenza dello Status)", "text": "Qualora il rapporto di conoscenza generi attrito o disagio classificabile come Rischio Critico, le Parti concordano formalmente la risoluzione dello status di \"Conoscente\". Da quel momento, i due soggetti si impegnano vincolativamente a comportarsi come estranei reciprocamente ignoti, sospendendo qualsiasi obbligo sociale di saluto o riconoscimento in pubblico."}
                ]
            }
        }
    },
    "CONVIVENZA": { 
        "header_suffix": "CONVIVENZA DOMESTICA",
        "levels": {
            1: {
                "title": "CAPITOLATO DI GESTIONE ORDINARIA",
                "subtitle": "Normativa quadro per l'igiene domestica di base e la civile coabitazione",
                "clauses": [
                    {"id": "Art. 1.1", "title": "Protocollo di Etichettatura dei Beni di Consumo", "text": "All'interno dei dispositivi di refrigerazione e nelle dispense condivise, ogni singolo bene alimentare o di consumo deve essere identificato in modo inequivocabile tramite apposita marcatura indelebile recante le iniziali o il codice identificativo del legittimo proprietario. I beni rinvenuti privi di tale marcatura saranno automaticamente riclassificati come \"Res Nullius\" (Cose di nessuno) e, in quanto tali, soggetti a confisca immediata, consumo libero o smaltimento d'ufficio da parte della controparte."},
                    {"id": "Art. 1.2", "title": "Termine Perentorio di Decadenza del Residuo Organico", "text": "È fatto divieto assoluto di depositare, abbandonare o stoccare stoviglie, posate o strumenti di cottura recanti residui organici all'interno del lavello per un lasso di tempo superiore ai 30 (trenta) minuti dal termine effettivo del pasto. Trascorso tale \"Periodo di Grazia\", il residuo viene formalmente riclassificato come \"Rischio Batteriologico Attivo\" e il soggetto responsabile è passibile di sanzione sociale o ammenda compensativa."},
                    {"id": "Art. 1.3", "title": "Divieto di Colonizzazione Territoriale delle Superfici", "text": "Le superfici orizzontali adibite all'uso comune (tavoli da pranzo, ripiani di lavoro, isole, sedute) devono essere integralmente sgomberate da qualsiasi effetto personale o residuo di attività al termine immediato del loro utilizzo. È severamente vietata la pratica della \"Sosta Passiva\", ovvero l'abbandono strategico di oggetti personali finalizzato alla marcatura territoriale o alla rivendicazione implicita dello spazio condiviso."},
                    {"id": "Art. 1.4", "title": "Soglie di Tolleranza Decibel Notturna", "text": "Nella fascia oraria protetta, convenzionalmente stabilita tra le ore 23:00 e le ore 07:00, l'emissione sonora proveniente da dispositivi elettronici di riproduzione o dall'apparato fonatorio dei Contraenti non deve eccedere la soglia critica di 40 (quaranta) decibel, misurati in corrispondenza della soglia di ingresso della stanza adiacente. Tale limite è inderogabile per garantire il diritto al riposo psicofisico."},
                    {"id": "Art. 1.5", "title": "Turnazione Rigida dei Servizi Igienici", "text": "In presenza di un unico servizio igienico all'interno dell'Unità Abitativa, l'occupazione della risorsa per finalità non strettamente fisiologiche (quali cosmesi, igiene profonda, relax o lettura) è contingentata in slot temporali indivisibili di massimo 15 (quindici) minuti. Nelle fasce orarie di picco mattutino, vige l'obbligo contrattuale di coordinamento preventivo degli accessi per evitare disservizi logistici."}
                ]
            },
            2: {
                "title": "PROTOCOLLO DI TUTELA DELLE RISORSE",
                "subtitle": "Regolamento per la protezione della proprietà individuale e la gestione dei confini",
                "clauses": [
                    {"id": "Art. 2.1", "title": "Protocollo Visti di Ingresso per Soggetti Terzi", "text": "L'accesso all'Unità Abitativa da parte di soggetti terzi non residenti (ospiti, partner non conviventi, familiari) è subordinato all'approvazione esplicita della controparte, da richiedersi con un preavviso minimo non inferiore alle 24 (ventiquattro) ore. Il \"Visto Ospiti\" emesso ha una validità temporale massima di ore 4 (quattro), salvo deroga scritta controfirmata da entrambi i Contraenti."},
                    {"id": "Art. 2.2", "title": "Divieto di Appropriazione Indebita di Consumabili", "text": "È fatto divieto di utilizzo unilaterale, anche parziale, di prodotti di consumo (a titolo esemplificativo: olio, detergenti, spezie, carta igienica) acquistati in via esclusiva dalla controparte, salvo l'avvenuta istituzione di un fondo cassa comune (\"Cassa di Compensazione\") gestito con criteri di trasparenza contabile e rendicontazione periodica."},
                    {"id": "Art. 2.3", "title": "Principio di Invarianza Termica Concordata", "text": "È vietata la modifica unilaterale e arbitraria dei parametri del termostato centralizzato o del regime di apertura degli infissi che comporti un'alterazione della temperatura media ambientale superiore a 2 (due) gradi Celsius. La regolazione del microclima domestico deve essere frutto di consenso unanime o, in difetto, calcolata rigorosamente sulle medie stagionali standard previste dalla normativa vigente."},
                    {"id": "Art. 2.4", "title": "Clausola di Neutralità Olfattiva", "text": "È proibita la saturazione degli spazi comuni con emissioni olfattive intense derivanti da pratiche di cucina invasiva, fumo di tabacco, incensi o profumazioni ambientali non preventivamente concordate. Ogni emissione olfattiva deve essere rigorosamente confinata all'interno dello spazio privato (Zona Rossa) del Contraente responsabile, mediante adeguata ventilazione."},
                    {"id": "Art. 2.5", "title": "Interdizione alla Comunicazione Asincrona Cartacea", "text": "È fatto divieto assoluto di comunicare disagi, accuse, recriminazioni o richiami tramite supporti cartacei lasciati in visibilità (es. foglietti adesivi su elettrodomestici), pratica classificata d'ufficio come \"Aggressività Passiva Analogica\". Ogni comunicazione di servizio o lamentela deve avvenire esclusivamente tramite piattaforme di messaggistica istantanea privata, al fine di garantire la tracciabilità e la marcatura temporale certa della lettura (Doppia Spunta)."}
                ]
            },
            3: {
                "title": "REGIME DI SEPARAZIONE DOMESTICA",
                "subtitle": "Norme per la segregazione finanziaria e spaziale",
                "clauses": [
                    {"id": "Art. 3.1", "title": "Automatismo dei Flussi Finanziari", "text": "I pagamenti relativi alle utenze, al canone di locazione e agli oneri accessori non possono essere gestiti tramite raccolta manuale di contante o anticipi personali discrezionali. È fatto obbligo di istituire un sistema di addebito automatico (RID) o bonifico ricorrente istantaneo, al fine di prevenire la genesi di posizioni debitorie latenti o contenziosi contabili tra i Contraenti."},
                    {"id": "Art. 3.2", "title": "Inviolabilità dello Spazio Privato (Zona Rossa)", "text": "Le camere da letto personali sono formalmente dichiarate \"Stati Sovrani\" a giurisdizione esclusiva. L'ingresso fisico o visivo della controparte è tassativamente vietato in assenza di invito esplicito e contestuale, anche in caso di porte lasciate accidentalmente aperte. È altresì vietato esprimere giudizi o commenti sullo stato di ordine, igiene o arredo presente all'interno delle Zone Rosse."},
                    {"id": "Art. 3.3", "title": "Razionamento delle Risorse Idriche ed Energetiche", "text": "Al fine di prevenire conflitti sui costi di gestione e sulla disponibilità delle risorse, l'utilizzo dell'acqua calda sanitaria è contingentato. L'Agenzia raccomanda l'installazione di dispositivi temporizzatori (timer doccia) o la definizione contrattuale di slot orari esclusivi per l'igiene personale, pena l'addebito del surplus di consumo."},
                    {"id": "Art. 3.4", "title": "Proibizione di Organismi Biologici Non Contrattualizzati", "text": "È fatto divieto assoluto di introdurre nell'ecosistema domestico organismi biologici (animali domestici, piante ornamentali ingombranti) o colture batteriche attive (es. lievito madre, kombucha) che richiedano cura condivisa, occupino spazio comune o generino odori, in assenza di uno specifico addendum contrattuale approvato all'unanimità."},
                    {"id": "Art. 3.5", "title": "Clausola di Stasi dell'Arredo Strutturale", "text": "È vietato procedere allo spostamento di mobilio, alla tinteggiatura di pareti o all'alterazione della disposizione degli oggetti ornamentali negli spazi comuni senza l'approvazione formale e preventiva della controparte. L'assetto dell'Unità Abitativa deve permanere nello stato di fatto originario (\"Status Quo Ante\") per evitare rivendicazioni territoriali o alterazioni dell'equilibrio estetico."}
                ]
            },
            4: {
                "title": "STATO DI DISSOCIAZIONE ABITATIVA",
                "subtitle": "Protocollo di convivenza estranea e segregazione funzionale",
                "clauses": [
                    {"id": "Art. 4.1", "title": "Segregazione Temporale dei Pasti", "text": "Al fine di eliminare alla radice le tensioni derivanti dalla convivialità forzata, è fatto divieto ai Contraenti di consumare i pasti nel medesimo ambiente (cucina o sala da pranzo) contemporaneamente. Verrà redatto un calendario vincolante di utilizzo esclusivo della cucina (\"Turni Mensa\"), la cui violazione costituisce grave inadempimento."},
                    {"id": "Art. 4.2", "title": "Obbligo di Isolamento Acustico Personale", "text": "Durante la permanenza o il transito negli spazi comuni (salotto, corridoi, ingresso), i Contraenti hanno l'obbligo tassativo di indossare dispositivi di cancellazione attiva del rumore (cuffie ANC) o tappi auricolari, al fine di garantire il reciproco isolamento sensoriale e prevenire l'avvio accidentale di interazioni verbali non necessarie."},
                    {"id": "Art. 4.3", "title": "Accesso alle Aree Comuni su Prenotazione", "text": "L'utilizzo del soggiorno, della televisione principale o di altre aree relax non è libero, bensì soggetto a un rigido sistema di prenotazione oraria tramite registro condiviso (cartaceo o digitale). Al di fuori del proprio slot prenotato, il Contraente ha l'obbligo di rimanere confinato all'interno della propria Zona Rossa (stanza privata)."},
                    {"id": "Art. 4.4", "title": "Intermediazione Digitale Domestica", "text": "È formalmente sospesa ogni forma di comunicazione verbale diretta tra i Contraenti all'interno del perimetro dell'abitazione. Qualsiasi richiesta operativa (es. \"Sposta l'auto\", \"Chiudi la porta\") deve essere inoltrata esclusivamente tramite messaggistica istantanea privata, anche qualora i soggetti si trovino nella stessa stanza, al fine di mantenere una traccia documentale certa ed evitare l'escalation di toni aggressivi."},
                    {"id": "Art. 4.5", "title": "Clausola di Dissoluzione Abitativa Immediata", "text": "In caso di persistenza dello stato di conflitto (Rischio Critico costante) per un periodo superiore a 30 giorni, i Contraenti conferiscono irrevocabilmente ad ALUA il potere decisionale (Potere di Veto) di recedere unilateralmente dal contratto di locazione per entrambi o di designare insindacabilmente un soggetto da espellere (\"Sfratto Selettivo\"), al fine di salvaguardare la vivibilità residua dell'Unità Abitativa."}
                ]
            }
        }
    }
}
